name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Install SLS Plugins and Deploy
      uses: serverless/github-action@master
      with:
        args: deploy --force --stage prod --verbose
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DOMAIN_NAME: battlelineproductions.com
        REDIRECT_DOMAIN_NAME: www.battlelineproductions.com
        NODE_ENV: production
        NUXT_TELEMETRY_DISABLED: '1'
        DOMAIN_HOSTED_ZONE: battlelineproductions.com.
        ASSETS_DOMAIN_NAME: cdn.battlelineproductions.com
        ASSETS_ACM_ARN: arn:aws:acm:us-east-1:098170852411:certificate/b19d95de-6177-446d-ae1f-45195e5b08b8
        MAILCHIMP_AUDIENCE_ID: ${{ secrets.MAILCHIMP_AUDIENCE_ID }}
        MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
